export const MainBodyBackground = "#F0F0F0"
export const tableLineBorderColor = "#DFDFDF"
export const searchPlaceHolderColor = "#9E9E9E"
export const searchInputColor  = "#DFDFDF"
export const gradientPrimaryColor = "#5A84C0"
export const gradientSecondColor = "#594ED2"
export const serachContainerH1 = "#1C1C1C"
